abstract: remember complex information without giving yourself a headache
author: Andrew Sterling Hanenkamp C<< <hanenkamp@cpan.org> >>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Data-Remember
no_index: 
  directory: 
    - inc
    - t
requires: 
  DBM::Deep: 1.0003
  POE: 0
  UNIVERSAL::require: 0
  YAML::Syck: 0
version: 0.05
